# Generated by Django 3.1.7 on 2021-03-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita_ingrediente', to='cookbook.receita'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidade_ingrediente', to='cookbook.unidademedida'),
        ),
    ]
